apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kuma-vs
  namespace: monitorizacion
spec:
  hosts:
  - "*"  # <--- Esto es el "asterisco". Significa: "Acepta cualquier nombre o IP"
  gateways:
  - produccion/app-gateway # <--- Usamos el portero que ya tenías del pulpo
  http:
  - route:
    - destination:
        host: uptime-kuma-svc # <--- El nombre de tu servicio que hemos visto en Lens
        port:
          number: 80 # <--- El puerto que hemos visto en Lens que mapea al 3001