apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data-pvc
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
        - containerPort: 3001
        # --- AQUÍ ESTÁ LA MAGIA ---
        volumeMounts:
        - name: kuma-storage
          mountPath: /app/data
      volumes:
      - name: kuma-storage
        persistentVolumeClaim:
          claimName: kuma-data-pvc
